# fly.toml app configuration file generated for moments on 2023-11-17T15:22:15-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "moments"
primary_region = "atl"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
